### ISSUE TITLE
verify rawheader failed

### ISSUE THREAD

**Issue by mailinglists35** [pizhenwei/atophttpd#2]
git clone...
make...
systemctl start atop
````
$ ./atophttpd -a 192.168.13.51
rawlog_parse_one: "/var/log/atop/atop_20230528" verify rawheader failed
./atophttpd runs with log path(/var/log/atop), port(2867)
Connection type tcp registered
ConnectionType tls not builtin
Ready to serve
````
oracle linux 9

**Comment by mailinglists35** [comment]
`atop -r /var/log/atop/atop_20230528` works

**Comment by pizhenwei** [comment]
> git clone... make... systemctl start atop
> 
> ```
> $ ./atophttpd -a 192.168.13.51
> rawlog_parse_one: "/var/log/atop/atop_20230528" verify rawheader failed
> ./atophttpd runs with log path(/var/log/atop), port(2867)
> Connection type tcp registered
> ConnectionType tls not builtin
> Ready to serve
> ```
> 
> oracle linux 9

Hi,
Currently, atophttpd supports atop-2.8 only.
atophttpd has a submodule `atop`, build this atop and install it, atophttpd should work.

**Comment by pizhenwei** [comment]
This is limitation by design.

**Comment by pizhenwei** [comment]
This is limitation by design.

**Comment by pizhenwei** [comment]
@mailinglists35 
Hi, would you please tell me your atop version? `atop -V` would be fine.

**Comment by mailinglists35** [comment]
atop-2.7.1-1.el9.x86_64

$ atop -V
Version: 2.7.1 - 2022/01/08 12:48:36     <gerlof.langeveld@atoptool.nl>

**Comment by mailinglists35** [comment]
> Currently, atophttpd supports atop-2.8 only.

sadly no 2.8 is available on rhel9 and clones

````
$ sudo -E dnf list available \*atop\*
Last metadata expiration check: 1:07:42 ago on Wed 17 Jan 2024 12:15:45 PM EET.
Available Packages
atop.src                                               2.7.1-1.el9                 ol9_developer_EPEL
````

**Comment by MeinhardZhou** [comment]
@mailinglists35

**Comment by MeinhardZhou** [comment]
@mailinglists35 

v2.7.1 & v2.7.0 is all already available.

**Comment by pizhenwei** [comment]
> @mailinglists35
> 
> v2.7.1 & v2.7.0 is all already available.

Hi, @mailinglists35 
Any feedback or suggestion?

**Comment by mailinglists35** [comment]
I will be able to validate the suggestions only in about a couple of weeks, thank you!
